In [2]:
import numpy as np


In [19]:
#printing array in numpy
a= np.array([[1,2,3,4,5,6,7],
            [7,6,5,4,3,2,1]])
print(a)

[[1 2 3 4 5 6 7]
 [7 6 5 4 3 2 1]]


In [17]:
#multidimension array
c= np.array([[1,4,5],[2,5,7],[1,7,8],[7,7,7]])
print(c)

[[1 4 5]
 [2 5 7]
 [1 7 8]
 [7 7 7]]


In [5]:
#get dimension
c.ndim

2

In [6]:
#strucure
c.shape

(4, 3)

In [7]:
#type
c.dtype

dtype('int32')

In [8]:
#get totalsize
c.size


12

In [9]:
d=np.array([[1,2,3,4],[5,6,7,8]])
print(d)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
#to get specific element[row,col]
d[1,3]

8

In [11]:
#get specific row
d[1, :]

array([5, 6, 7, 8])

In [12]:
#to get specific colomun
d[: ,2]

array([3, 7])

In [23]:
#slicing[starting:end:step]
e=np.array([[1,2,3,4,5,6,7],
            [7,6,5,4,3,2,1]])
e[1, 1:-2:2]
e[0, 1:-1:2]

array([2, 4, 6])

In [31]:
#the element can change
a[0,4]=10
print(a)

#change the column element
a[: ,2]=0
print(a)
#also
a[: ,3]=[2,3]
print(a)

[[ 1  2  0  2 10  6  7]
 [ 7  6  0  3  3  2  1]]
[[ 1  2  0  2 10  6  7]
 [ 7  6  0  3  3  2  1]]
[[ 1  2  0  2 10  6  7]
 [ 7  6  0  3  3  2  1]]


In [38]:
#3d array
b=np.array([[[1,2],[4,3]],[[5,6],[8,7]]])
print(b)



[[[1 2]
  [4 3]]

 [[5 6]
  [8 7]]]


In [39]:
#get a specify element(work outside in)
b[1,0,0]

5

In [41]:
#to seperate the 3d array to normal array
b[:,1,:]

array([[4, 3],
       [8, 7]])

In [46]:
#replace
b[:,1,:]=[[9,9],[8,8]]

In [47]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [49]:
#initialize
# all zero matrix
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.zeros((2,3,3),dtype='int32')

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [52]:
#any other number((shape),number)
np.full((2,3),11)


array([[11, 11, 11],
       [11, 11, 11]])

In [54]:
#any other number(full_like)access the previous array
np.full_like(a,4)
#or
np.full(a.shape,3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [55]:
#random decimal number
np.random.rand(4,3)

array([[0.63491855, 0.01709054, 0.7654843 ],
       [0.50926436, 0.30392871, 0.62629841],
       [0.57930775, 0.00633047, 0.21280304],
       [0.02572694, 0.63440467, 0.38421583]])

In [64]:
#random integer number
np.random.randint(3,size=(3,3))
#the front of size is will give the random value in the array

array([[2, 1, 2],
       [1, 2, 1],
       [2, 2, 0]])

In [66]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])